model:
  name: allenai/OLMo-2-1124-7B
  size: 7b
  args_collect_kfac:
    batch_size: 24
method:
  name: bergson
  use_eigenvalue_corrections: true
  collect_script: memorization_kfac/data/collect_kfac_bergson.py
  bergson_factors_arg: --bergson-factors out/collect_kfac/bergson/7b
benchmark:
  args:
    task: gsm8k::olmes
    batch-size: 32
fsdp: false
world_size: null
collect_kfac:
  sample_labels: true
  args:
    device: cuda
    dtype: bfloat16
    corpus: dolmo
    nbytes: 100000000
    seq_len: 512
    target_blocks:
    - '23'
    - '24'
    - '25'
eval_kfac:
  _layers:
    7b:
      goodfire:
        '23':
          gate: 0.6
          up: 0.6
          down: 1.0
        '24':
          gate: 0.6
          up: 0.6
          down: 1.0
        '25':
          gate: 0.6
          up: 0.6
          down: 1.0
      bergson:
        '23':
          gate: 0.4
          up: 0.4
          down: 1.0
        '24':
          gate: 0.4
          up: 0.4
          down: 1.0
        '25':
          gate: 0.4
          up: 0.4
          down: 1.0
    1b:
      goodfire:
        '13':
          gate: 0.6
          up: 0.6
          down: 1.0
        '14':
          gate: 0.6
          up: 0.6
          down: 1.0
        '15':
          gate: 0.6
          up: 0.6
          down: 1.0
      bergson:
        '13':
          gate: 0.4
          up: 0.4
          down: 1.0
        '14':
          gate: 0.4
          up: 0.4
          down: 1.0
        '15':
          gate: 0.4
          up: 0.4
          down: 1.0
  layers:
    '23':
      gate: 0.4
      up: 0.4
      down: 1.0
    '24':
      gate: 0.4
      up: 0.4
      down: 1.0
    '25':
      gate: 0.4
      up: 0.4
      down: 1.0
  args:
    bs: 96
    model-size: 7b
    results-tag: 7b
    layers-json: '{"23": {"gate": 0.4, "up": 0.4, "down": 1.0}, "24": {"gate": 0.4,
      "up": 0.4, "down": 1.0}, "25": {"gate": 0.4, "up": 0.4, "down": 1.0}}'
    layers_per_pass: 3
out_suffix: bergson/7b
out_dir:
  collect_kfac: out/collect_kfac/bergson/7b
  eval_kfac: out/eval_kfac/bergson/7b
  plot_figure2: out/plot_figure2/bergson/7b
  benchmark: out/benchmark/bergson/7b
computed:
  eigenvalue_corrections_flag: --eigenvalue-corrections
  sample_labels_flag: --sample_labels
  fsdp_flag: ''
  world_size_flag: ''
