# @package model
name: "allenai/OLMo-2-0425-1B"
size: "1b"

args_collect_kfac:
  batch_size: 32
  target_blocks: "13 14 15"  # Keep in sync with eval_kfac._preserved_energy

args_eval_kfac:
  layers_per_pass: 3

